name: Build and Deploy RabbitMQ Publisher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: registry.digitalocean.com/clubz-platform-registry
  IMAGE_NAME: clubz-rabbitmq-publisher

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build container image
      run: docker build --platform linux/amd64 -t $REGISTRY/$IMAGE_NAME:$GITHUB_SHA -t $REGISTRY/$IMAGE_NAME:latest .

    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: |
        docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
        docker push $REGISTRY/$IMAGE_NAME:latest

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 clubz-platform-cluster

    - name: Deploy to DigitalOcean Kubernetes
      run: |
        kubectl set image deployment/clubz-rabbitmq-publisher clubz-rabbitmq-publisher=$REGISTRY/$IMAGE_NAME:$GITHUB_SHA -n clubz-dev
        kubectl rollout status deployment/clubz-rabbitmq-publisher -n clubz-dev

    - name: Verify deployment
      run: kubectl get services -n clubz-dev
